name: bitebyte
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  flutter_modular: ^5.0.3
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  asuka: ^2.2.0
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  sqflite: ^2.3.0
  uuid: ^3.0.4
  video_player: ^2.2.14
  permission_handler: ^11.3.0
  flutter_speed_dial: ^7.0.0

  flutter_localizations:
    sdk: flutter
  progress_dialog_null_safe: ^1.0.7
  pdf: ^3.10.8
  share_extend: ^2.0.0
  path_provider: ^2.1.3
  flutter_pdfview: ^1.2.1
  syncfusion_flutter_pdfviewer: ^23.1.39
  android_path_provider: ^0.3.0
  share: ^2.0.4
  open_file: ^3.2.1
  external_path: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.2.0

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/
    - assets/gifs/
    - .env

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/imagens/logobitebyte.jpg"
