import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class UiConfig {
  UiConfig._();

  static String get title => 'NeoColetorFacil';

  static ThemeData get themelight => ThemeData(
        useMaterial3: true,
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF006E00),
          foregroundColor: Color(0xFFFFFFFF),
          titleTextStyle: TextStyle(
            color: Color(0xFFFFFFFF),
            fontSize: 20.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.15,
          ),
          toolbarTextStyle: TextStyle(
            color: Color(0xFFFFFFFF),
            fontSize: 14.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.15,
          ),
          systemOverlayStyle: SystemUiOverlayStyle(
            statusBarColor: Color(0xFF006E00),
            statusBarIconBrightness: Brightness.light,
            statusBarBrightness: Brightness.light,
            systemNavigationBarColor: Color(0xFF006E00),
            systemNavigationBarDividerColor: Color(0xFF006E00),
            systemNavigationBarIconBrightness: Brightness.light,
          ),
        ),
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xFF006E00),
          onPrimary: Color(0xFFFFFFFF),
          primaryContainer: Color(0xFF8DFB77),
          onPrimaryContainer: Color(0xFF002200),
          secondary: Color(0xFF2F6B26),
          onSecondary: Color(0xFFFFFFFF),
          secondaryContainer: Color(0xFFB0F49E),
          onSecondaryContainer: Color(0xFF002200),
          tertiary: Color(0xFF306B25),
          onTertiary: Color(0xFFFFFFFF),
          tertiaryContainer: Color(0xFFB1F49D),
          onTertiaryContainer: Color(0xFF012200),
          error: Color(0xFFBA1A1A),
          errorContainer: Color(0xFFFFDAD6),
          onError: Color(0xFFFFFFFF),
          onErrorContainer: Color(0xFF410002),
          background: Color(0xFFFCFDF6),
          onBackground: Color(0xFF1A1C18),
          surface: Color(0xFFFCFDF6),
          onSurface: Color(0xFF1A1C18),
          surfaceVariant: Color(0xFFDFE4D7),
          onSurfaceVariant: Color(0xFF43483F),
          outline: Color(0xFF73796E),
          onInverseSurface: Color(0xFFF1F1EB),
          inverseSurface: Color(0xFF2F312D),
          inversePrimary: Color(0xFF72DE5E),
          shadow: Color(0xFF000000),
          surfaceTint: Color(0xFF006E00),
          outlineVariant: Color(0xFFC3C8BC),
          scrim: Color(0xFF000000),
        ),
      );

  static ThemeData get themedark => ThemeData(
        useMaterial3: true,
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF006E00),
          foregroundColor: Color(0xFFFFFFFF),
          titleTextStyle: TextStyle(
            color: Color(0xFFFFFFFF),
            fontSize: 20.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.15,
          ),
          toolbarTextStyle: TextStyle(
            color: Color(0xFFFFFFFF),
            fontSize: 14.0,
            fontWeight: FontWeight.w500,
            letterSpacing: 0.15,
          ),
          systemOverlayStyle: SystemUiOverlayStyle(
            statusBarColor: Color(0xFF006E00),
            statusBarIconBrightness: Brightness.light,
            statusBarBrightness: Brightness.light,
            systemNavigationBarColor: Color(0xFF006E00),
            systemNavigationBarDividerColor: Color(0xFF006E00),
            systemNavigationBarIconBrightness: Brightness.light,
          ),
        ),
        colorScheme: const ColorScheme(
          brightness: Brightness.dark,
          primary: Color(0xFF72DE5E),
          onPrimary: Color(0xFF003A00),
          primaryContainer: Color(0xFF005300),
          onPrimaryContainer: Color(0xFF8DFB77),
          secondary: Color(0xFF95D784),
          onSecondary: Color(0xFF003A00),
          secondaryContainer: Color(0xFF15520F),
          onSecondaryContainer: Color(0xFFB0F49E),
          tertiary: Color(0xFF96D783),
          onTertiary: Color(0xFF023A00),
          tertiaryContainer: Color(0xFF16520E),
          onTertiaryContainer: Color(0xFFB1F49D),
          error: Color(0xFFFFB4AB),
          errorContainer: Color(0xFF93000A),
          onError: Color(0xFF690005),
          onErrorContainer: Color(0xFFFFDAD6),
          background: Color(0xFF1A1C18),
          onBackground: Color(0xFFE2E3DC),
          surface: Color(0xFF1A1C18),
          onSurface: Color(0xFFE2E3DC),
          surfaceVariant: Color(0xFF43483F),
          onSurfaceVariant: Color(0xFFC3C8BC),
          outline: Color(0xFF8D9387),
          onInverseSurface: Color(0xFF1A1C18),
          inverseSurface: Color(0xFFE2E3DC),
          inversePrimary: Color(0xFF006E00),
          shadow: Color(0xFF000000),
          surfaceTint: Color(0xFF72DE5E),
          outlineVariant: Color(0xFF43483F),
          scrim: Color(0xFF000000),
        ),
      );
}
